{{- if .Values.express.enabled }}

{{ $componentName := "express" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-print-server
  labels:
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    {{- include "pace.labels.deployTag" . | nindent 4 }}
    rohea.com/stop-during-deploy: 'true'
  annotations:
    {{- include "pace.annotations.change-cause" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pace.labels.component" $componentDict | nindent 6 }}
  progressDeadlineSeconds: 540
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        rohea.com/stop-during-deploy: 'true'
    spec:
      automountServiceAccountToken: false
      containers:
        - name: express
          image: {{ .Values.express.image }}
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: 'https://{{ .Values.ingress.deployUrl }}/api'
            - name: HOSTNAME
              value: '0.0.0.0'
            - name: PORT
              value: '3030'
          {{- if .Values.enableKubernetesProbes }}
          livenessProbe:
            httpGet:
              port: 3030
              path: /print/test?preview=1
            initialDelaySeconds: 30
          {{- end }}
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
