{{- if .Values.express.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: express-print-server
spec:
  selector:
    rohea.com/installation: {{ .Values.installationSlug }}
    rohea.com/app: pace
    rohea.com/component: express
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3030

{{- end }}
