{{- if .Values.networkPolicies.enabled }}
{{- if .Values.express.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: express-network-policy
  labels:
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      rohea.com/component: express

  ingress:
    - from:
        - podSelector:
            matchLabels:
              rohea.com/component: web

      ports:
        - protocol: TCP
          port: 3030

{{- end }}
{{- end }}
