{{- if .Values.heartbeat.enabled }}

{{/*
NOTE: This resource requires that a secret 'heartbeat-secret-config' exists in the deployed namespace.
      Create it with:
        k create secret generic heartbeat-secret-config \
          --from-literal ES_USERNAME=username \
          --from-literal ES_PASSWORD=password \
          --from-literal ES_URL=logs.rohea.com:9200
*/}}

{{ $componentName := "heartbeat" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: heartbeat
  labels:
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    rohea.com/stop-during-deploy: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pace.labels.component" $componentDict | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        rohea.com/stop-during-deploy: 'true'
    spec:
      automountServiceAccountToken: false
      containers:
        - name: heartbeat
          image: {{ .Values.heartbeat.image.repository }}:{{ .Values.heartbeat.image.tag }}
          envFrom:
            - secretRef:
                name: heartbeat-secret-config
          volumeMounts:
            - mountPath: /usr/share/heartbeat/heartbeat.yml
              name: config
              readOnly: true
              subPath: heartbeat.yml
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            defaultMode: 0640
            name: heartbeat-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-config
data:
  heartbeat.yml: |-
    output.elasticsearch:
      # Note: the following environment variables should come from the 'heartbeat-secret-config' resource.
      #       See the heartbeat.yaml template file header comment.
      hosts: [ '${ES_URL}' ]
      protocol: "https"
      username: "${ES_USERNAME}"
      password: "${ES_PASSWORD}"

    heartbeat:
      monitors:

      - type: http
        id: {{ required "Value heartbeat.monitor.id is required when heartbeat is enabled" .Values.heartbeat.monitor.id }}-smoketest-monitor
        name: {{ required "Value heartbeat.monitor.name is required when heartbeat is enabled" .Values.heartbeat.monitor.name }} API
        urls:
          - "{{ required "Value heartbeat.monitor.url is required when heartbeat is enabled" .Values.heartbeat.monitor.url }}/api/public/status/smokecheck"
        schedule: '@every 30s'
        check.response:
          status: 200

      - type: http
        id: {{ required "Value heartbeat.monitor.id is required when heartbeat is enabled" .Values.heartbeat.monitor.id }}-https-monitor
        name: {{ required "Value heartbeat.monitor.name is required when heartbeat is enabled" .Values.heartbeat.monitor.name }} Frontpage
        urls:
          - "{{ required "Value heartbeat.monitor.url is required when heartbeat is enabled" .Values.heartbeat.monitor.url }}"
        schedule: '@every 30s'
        check.response:
          status: 200

      run_from:
        id: pace-helm
        geo:
          name: Pace Helm
{{ end }}