apiVersion: v1
kind: Service
metadata:
  name: maintenance-page
  labels:
    rohea.com/installation: {{ .Values.installationSlug }}
    rohea.com/app: pace
    rohea.com/component: maintenance-page
spec:
  selector:
    rohea.com/installation: {{ .Values.installationSlug }}
    rohea.com/app: pace
    rohea.com/component: maintenance-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80