{{- if .Values.networkPolicies.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: maintenance-network-policy
  labels:
    {{- include "pace.labels.deployTag" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      rohea.com/component: maintenance-page

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              pace.rohea.com/component-namespace: ingress

      ports:
        - protocol: TCP
          port: 80

{{- end }}