{{- if .Values.mercure.enabled }}

{{ $componentName := "mercure" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $componentName }}
  labels:
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
    rohea.com/stop-during-deploy: 'true'
    rohea.com/collect_metrics: 'true'
  annotations:
    {{- include "pace.annotations.change-cause" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pace.labels.selectorLabels" $componentDict | nindent 6 }}
  replicas: 1
  progressDeadlineSeconds: 60
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        rohea.com/stop-during-deploy: 'true'
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ $componentName }}
          image: {{ .Values.mercure.image.repository }}:{{ .Values.mercure.image.tag }}
          {{- if .Values.mercure.debug }}
          args:
            - caddy
            - run
            - --config
            - /etc/caddy/Caddyfile.dev
          {{- end }}
          ports:
            - containerPort: 80
          imagePullPolicy: Always

          envFrom:
            - secretRef:
                name: mercure
            - configMapRef:
                 name: mercure-helm

          resources:
            requests:
              memory: 50Mi
              cpu: 10m
            limits:
              memory: 100Mi
              cpu: 100m
{{- end }}
