{{- if .Values.mercure.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mercure
  annotations:
    {{- include "pace.annotations.ingress" (dict "local" .Values.ingress.main "main" $.Values.ingress.main) | nindent 4 }}
  labels:
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
    pace.rohea.com/component: pace-ingress
spec:
  {{- if .Values.ingress.main.tls.enabled }}
  tls:
    - hosts:
      - "mercure.{{- required "Configuration key 'ingress.main.deployUrl' is required" .Values.ingress.main.deployUrl }}"
      secretName: letsencrypt-tls-pace-mercure
  {{- end }}
  rules:
    - host: mercure.{{ .Values.ingress.main.deployUrl }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mercure
                port:
                  number: 80

{{- end }}
