{{ $componentName := "messenger-consumer-sequential" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: messenger-consumer-sequential
  labels:
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
    rohea.com/stop-during-deploy: 'true'
    rohea.com/collect_metrics: 'true'
  annotations:
    {{- include "pace.annotations.change-cause" . | nindent 4 }}
    rohea.com/target-replicas: '1'
spec:
  # We always want only one replica of the sequential consumer, so that the messages are ensured to be processed
  # in order of submission.
  replicas: 1
  selector:
    matchLabels:
      {{- include "pace.labels.selectorLabels" $componentDict | nindent 6 }}
  progressDeadlineSeconds: 300
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        pace.rohea.com/allow-network-db: "true"
        rohea.com/stop-during-deploy: 'true'
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- include "pace-php.security.runAsRohea" . | nindent 8 }}
      serviceAccountName: {{ .Values.web.serviceAccountName }}
      containers:
        - name: messenger-consumer
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          args:
            - messenger-sequential
          imagePullPolicy: Always
          envFrom:
            {{- include "pace.envFrom" . | nindent 12 }}
            {{- with .Values.web.envFrom }}{{- toYaml . | nindent 12 }}{{- end }}
          volumeMounts:
            {{- include "pace.volumeMounts" . | nindent 12 }}
            {{- with .Values.web.volumeMounts }}{{- toYaml . | nindent 12 }}{{- end}}
          resources:
            {{- toYaml .Values.messengerConsumers.resources | nindent 12 }}
      volumes:
        {{- include "pace.volumes" . | nindent 8 }}
        {{- with .Values.web.volumes }}{{- toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
