{{- if .Values.migrationsJob.enabled }}

{{ $componentName := "pace-database-migrations" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

apiVersion: batch/v1
kind: Job
metadata:
  name: pace-database-migrations-{{ .Values.migrationsJob.datetime }}
  labels:
    rohea.com/collect_metrics: 'true'
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        pace.rohea.com/allow-network-db: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- include "pace-php.security.runAsRohea" . | nindent 8 }}
      restartPolicy: Never
      serviceAccountName: {{ .Values.web.serviceAccountName }}
      containers:
        - name: migrations
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          args:
            - migrations
          imagePullPolicy: Always
          resources:
            {{- toYaml .Values.migrationsJob.resources | nindent 12 }}
          env:
            {{- range $k, $v := .Values.migrationsJob.env }}
            - name: "{{ $k }}"
              value: "{{ $v }}"
            {{- end }}
          envFrom:
            {{- include "pace.envFrom" . | nindent 12 }}
            {{- with .Values.web.envFrom }}{{- toYaml . | nindent 12 }}{{- end }}
            {{- include "pace.migrations.envFrom" . | nindent 12 }}
          volumeMounts:
            {{- include "pace.volumeMounts" . | nindent 12 }}
            {{- with .Values.web.volumeMounts }}{{- toYaml . | nindent 12 }}{{- end }}
      volumes:
        {{- include "pace.volumes" . | nindent 8 }}
        {{- with .Values.web.volumes }}{{- toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}