{{- if .Values.mongoAtlasLogforwarder.enabled }}

{{ $componentName := "mongo-atlas-logforwarder" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-atlas-logforwarder
  labels:
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    {{- include "pace.labels.deployTag" . | nindent 4 }}
  annotations:
    {{- include "pace.annotations.change-cause" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pace.labels.component" $componentDict | nindent 6 }}
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        rohea.com/stop-during-deploy: 'true'
        pace.rohea.com/allow-network-db: "true"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: logforwarder
          image: {{ .Values.mongoAtlasLogforwarder.image }}
          args:
            - '$(CLUSTER_NAME)'
            - '$(GROUP_ID)'
            - '$(PUBKEY)'
            - '$(PRIVKEY)'
          imagePullPolicy: Always
          env:
            - name: CLUSTER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-forwarder
                  key: CLUSTER_NAME
            - name: GROUP_ID
              valueFrom:
                secretKeyRef:
                  name: mongo-forwarder
                  key: GROUP_ID
            - name: PUBKEY
              valueFrom:
                secretKeyRef:
                  name: mongo-forwarder
                  key: PUBKEY
            - name: PRIVKEY
              valueFrom:
                secretKeyRef:
                  name: mongo-forwarder
                  key: PRIVKEY
          resources:
              requests:
                  memory: 32Mi
                  cpu: 0.01
              limits:
                  memory: 256Mi
                  cpu: 0.5
          volumeMounts:
            - mountPath: /mnt/dummy
              name: atlas-config-secret-volume
      volumes:
        - name: atlas-config-secret-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: mongoatlas-secret-provider
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}