{{- if .Values.paceDev.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-pacedev
  annotations:
    {{- include "pace.annotations.ingress" (dict "local" .Values.ingress.main "main" $.Values.ingress.main) | nindent 4 }}

    {{- with .Values.ingress.common.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
    pace.rohea.com/component: pace-ingress
spec:
  {{- if .Values.ingress.main.tls.enabled }}
  tls:
    - hosts:
      - "pacedev.{{- required "Configuration key 'ingress.main.deployUrl' is required" .Values.ingress.main.deployUrl }}"
      secretName: letsencrypt-tls-pace-pacedev
  {{- end }}
  rules:
    - host: pacedev.{{ .Values.ingress.main.deployUrl }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: pacedev
                port:
                  number: 80

{{- end }}
