{{/* Configmap loaded by all PHP pods */}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: php-helm
data:
  APP_ENV: {{ .Values.php.appEnv }}
  URI_SCHEME: https
  BASEURL: {{ .Values.php.baseUrl }}
  BEHIND_TRUSTED_PROXY: 'true'
  CORS_ALLOW_MULTIPLE_ORIGIN: {{ .Values.php.corsAllowMultipleOrigin | quote }}
  PHP_IDE_CONFIG: "serverName={{ .Values.installationSlug }}"
  {{- with .Values.php.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
