{{- if .Values.postfix.enabled }}

{{ $componentName := "postfix" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  labels:
    rohea.com/collect_metrics: 'true'
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pace.labels.selectorLabels" $componentDict | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postfix
          image: {{ .Values.postfix.image }}
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: postfix-helm
          {{- if not .Values.postfix.hostname }}
          # Unless postfix.hostname is explicitly provided, the node's name will be used in postfix
          env:
            - name: POSTFIX_myhostname
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          {{- end }}

          # The startup takes a few seconds.
          # When the supervisor pidfile is present, the startup is in the last stage so we assume it's ok.
          startupProbe:
            exec:
              command:
                - cat
                - /tmp/supervisord.pid
            initialDelaySeconds: 7
            periodSeconds: 5
            failureThreshold: 20

          volumeMounts:
            - name: dkimkeys  # This is only populated when the 'dkimkeys' secret exists in the namespace. If not, this has no effect.
              mountPath: "/etc/opendkim/keys"
              readOnly: true
          resources:
            requests:
              memory: 64Mi
              cpu: 10m
            limits:
              memory: 128Mi
              cpu: 100m
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      # Prefer scheduling the postfix pod on an explicitly labelled node. This is an affinity, not a selector,
      # so that if there is no such labelled node, the pod will be scheduled anywhere.
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: rohea.com/node-email-sender
                    operator: In
                    values:
                      - 'true'
              weight: 1

      volumes:
        - name: dkimkeys
          secret:
            secretName: dkimkeys
            optional: true

{{- end }}