{{- if .Values.postfix.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: postfix
spec:
  selector:
    rohea.com/installation: {{ .Values.installationSlug }}
    rohea.com/app: pace
    rohea.com/component: postfix
  ports:
    - name: http
      protocol: TCP
      port: 587

{{- end }}