{{ $componentName := "scheduler" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    rohea.com/collect_metrics: 'true'
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
    rohea.com/stop-during-deploy: 'true'
  annotations:
    {{- include "pace.annotations.change-cause" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pace.labels.selectorLabels" $componentDict | nindent 6 }}
  progressDeadlineSeconds: 300
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        pace.rohea.com/allow-network-db: "true"
        rohea.com/stop-during-deploy: 'true'
    spec:
      automountServiceAccountToken: false
      serviceAccountName: {{ .Values.web.serviceAccountName }}
      securityContext:
        {{- include "pace-php.security.runAsRohea" . | nindent 8 }}
        {{- with .Values.scheduler.podSecurityContext }}{{- toYaml . | nindent 8 }}{{- end }}
      containers:
        - name: scheduler
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          args:
            - scheduler
          imagePullPolicy: Always
          envFrom:
            {{- include "pace.envFrom" . | nindent 12 }}
            {{- with .Values.web.envFrom }}{{- toYaml . | nindent 12 }}{{- end }}
          volumeMounts:
            {{- include "pace.volumeMounts" . | nindent 12 }}
            {{- with .Values.web.volumeMounts }}{{- toYaml . | nindent 12 }}{{- end}}
            {{- with .Values.scheduler.volumeMounts }}{{- toYaml . | nindent 12 }}{{- end}}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
      volumes:
        {{- include "pace.volumes" . | nindent 8 }}
        {{- with .Values.web.volumes }}{{- toYaml . | nindent 8 }}{{- end }}
        {{- with .Values.scheduler.volumes }}{{- toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
