# Placeholder comment so that this file is rendered even if it does not contain any actual resources

{{- range $name, $definition := .Values.secretProviderClasses }}

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $definition.name }}
spec:
  provider: {{ $definition.provider }}
  parameters:
    {{- if eq $definition.provider "azure" }}
    useVMManagedIdentity: "true"
    tenantId: "{{ $definition.azure.tenantId }}"
    userAssignedIdentityID: "{{ $definition.azure.userAssignedIdentityID }}"
    keyvaultName: "{{ $definition.azure.keyvaultName }}"
    {{- end }}
    objects: |
      {{- $definition.objects | nindent 6 }}

    {{- if $definition.secretObjects }}
  secretObjects:
    {{- $definition.secretObjects | toYaml | nindent 4 }}
  {{- end }}

{{- end }}
