{{ $componentName := "statsd" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: statsd
  labels:
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    rohea.com/stop-during-deploy: 'true'
  annotations:
    {{- include "pace.annotations.change-cause" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pace.labels.component" $componentDict | nindent 6 }}
  progressDeadlineSeconds: 180
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        pace.rohea.com/allow-network-db: "true"
        rohea.com/stop-during-deploy: 'true'
    spec:
      automountServiceAccountToken: false
      containers:
        - name: statsd
          image: {{ .Values.statsd.image }}
          ports:
            - containerPort: 8125
              protocol: UDP
          imagePullPolicy: Always
          envFrom:
            {{- include "pace.statsd.envFrom" . | nindent 12 }}
          volumeMounts:
            {{- include "pace.statsd.volumeMounts" . | nindent 12 }}
          resources:
            requests:
              memory: 50Mi
              cpu: 0.01
            limits:
              memory: 150Mi
              cpu: 0.1
      volumes:
        {{- include "pace.statsd.volumes" . | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}