{{- if .Values.statsd.enabled }}
{{- if .Values.networkPolicies.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: statsd-network-policy
  labels:
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      rohea.com/component: statsd

  ingress:
    - from:
        - podSelector:
            matchLabels:
              rohea.com/component: web

      ports:
        - protocol: UDP
          port: 8125

{{- end }}
{{- end }}