{{- if .Values.statsd.enabled }}

{{ $componentName := "statsd" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

apiVersion: v1
kind: Service
metadata:
  name: statsd
  labels:
    rohea.com/collect_metrics: 'true'
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
spec:
  selector:
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
  ports:
    - protocol: UDP
      port: 8125
      targetPort: 8125

{{- end }}