{{ $componentName := "web" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

{{- if not (has .Values.deployContext .Values.availableContexts) }}
{{ $msg := print "deployContext is '" .Values.deployContext "' but only " .Values.availableContexts " are supported." }}
{{- fail $msg }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace
  labels:
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    {{- include "pace.labels.deployTag" . | nindent 4 }}
    rohea.com/stop-during-deploy: 'true'
  annotations:
    {{- include "pace.annotations.change-cause" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pace.labels.component" $componentDict | nindent 6 }}
  progressDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        rohea.com/stop-during-deploy: 'true'
        pace.rohea.com/allow-network-db: "true"
    spec:
      automountServiceAccountToken: false
      containers:
        - name: php-nginx
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          args:
            - web
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            {{- include "pace.envFrom" . | nindent 12 }}
          volumeMounts:
            {{- include "pace.volumeMounts" . | nindent 12 }}
            {{- with .Values.web.volumeMounts }}{{- toYaml . | nindent 12 }}{{- end}}
          {{- if .Values.enableKubernetesProbes }}
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/public/status/smokecheck
            initialDelaySeconds: 30
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
        {{- include "deployment.sentry-relay" . | nindent 8 }}
      volumes:
        {{- include "pace.volumes" . | nindent 8 }}
        {{- with .Values.web.volumes }}{{- toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}