apiVersion: v1
kind: Service
metadata:
  name: pace
  labels:
    rohea.com/collect_metrics: 'true'
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
spec:
  selector:
    rohea.com/installation: {{ .Values.installationSlug }}
    rohea.com/app: pace
    rohea.com/component: web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080