{{ $componentName := "web" }}
{{ $componentDict := dict "component" $componentName "global" $.Values }}

{{- if not (has .Values.deployContext .Values.availableContexts) }}
{{ $msg := print "deployContext is '" .Values.deployContext "' but only " .Values.availableContexts " are supported." }}
{{- fail $msg }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pace
  labels:
    {{- include "pace.labels.component" $componentDict | nindent 4 }}
    {{- include "pace.labels.deployTag" $ | nindent 4 }}
    rohea.com/stop-during-deploy: 'true'
    rohea.com/collect_metrics: 'true'
  annotations:
    {{- include "pace.annotations.change-cause" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pace.labels.selectorLabels" $componentDict | nindent 6 }}
  progressDeadlineSeconds: 300
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "pace.labels.component" $componentDict | nindent 8 }}
        rohea.com/stop-during-deploy: 'true'
        pace.rohea.com/allow-network-db: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- include "pace-php.security.runAsRohea" . | nindent 8 }}
      serviceAccountName: {{ .Values.web.serviceAccountName }}
      containers:
        - name: php-nginx
          image: {{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}
          args:
            - web
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          envFrom:
            {{- include "pace.envFrom" . | nindent 12 }}
            {{- with .Values.web.envFrom }}{{- toYaml . | nindent 12 }}{{- end }}
            - configMapRef:
                name: pace-helm
          volumeMounts:
            - name: jwt-secret-volume
              readOnly: true
              mountPath: "/pace/config/jwt/kubernetes/"
            {{- include "pace.volumeMounts" . | nindent 12 }}
            {{- with .Values.web.volumeMounts }}{{- toYaml . | nindent 12 }}{{- end}}
          {{- if .Values.enableKubernetesProbes }}
          startupProbe:
            httpGet:
              port: 8080
              path: /api/config
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/config
            initialDelaySeconds: 30
            periodSeconds: 60
            failureThreshold: 5
            timeoutSeconds: 30
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: jwt-secret-volume
          secret:
            secretName: jwt
        {{- include "pace.volumes" . | nindent 8 }}
        {{- with .Values.web.volumes }}{{- toYaml . | nindent 8 }}{{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}