{{- if .Values.networkPolicies.enabled }}

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pace-network-policy
spec:
  podSelector:
    matchLabels:
      rohea.com/component: web

  ingress:
    - from:
        - podSelector:
            matchLabels:
              rohea.com/component: express
        - namespaceSelector:
            matchLabels:
              pace.rohea.com/component-namespace: ingress

      ports:
        - protocol: TCP
          port: 8080

{{- end }}